---
- name: Creates directory
  file:
    path: ~/backend
    state: directory
    mode: 0755

- name: Extract artifact.tar.gz into ~/backend
  ansible.builtin.unarchive:
    src: ~/project/artifact.tar.gz
    dest: ~/backend

- name: install and run npm build
  shell: |
    cd ~/backend 
    ls -lart 
    node -v
    npm install -g n
    n 13.8.0
    hash -r
    node --version
    npm -v
    npm run build

- name: start pm2
  shell: |
    cd ~/backend
    pm2 stop default
    pm2 start npm --name backend -- start
