---
- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Creates directory
  file:
    path: ~/backend
    state: directory
    mode: 0755

- name: Extract artifact.tar.gz into ~/backend
  ansible.builtin.unarchive:
    src: ~/project/artifact.tar.gz
    dest: ~/backend


- name: install and run npm build
  shell: |
    cd ~/backend 
    ls -lart 
    node -v
    npm install --save --legacy-peer-deps
    npm run build 
    npm audit fix --audit-level=critical --force


- name: start pm2
  shell: |
    cd ~/backend
    pm2 stop default
    pm2 start npm --name backend -- start