---
- name: "update apt packages."
  become: true
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: true
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: true
  apt:
    autoremove: yes

- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present


- name: Extract artifact.tar.gz into ~/web
  ansible.builtin.unarchive:
    src: ~/project/artifact.tar.gz
    dest: ~/


- name: Executing node
  shell: |
    npm i
    pm2 stop default
    pm2 start npm -- run start
    cd dist
    pm2 start main.js --update-env