---
- name: Creates directory
  file:
    path: ~/backend
    state: directory
    mode: 0755

- name: Extract artifact.tar.gz into ~/backend
  ansible.builtin.unarchive:
    src: ~/project/artifact.tar.gz
    dest: ~/backend

- name: install npm v13.8.0
  become: true
  shell: |
    node -v
    npm install -g n
    n 13.8.0
    npm install -g pm2
    node --version
    npm -v

- name: start pm2
  shell: |
    /usr/bin/pm2 start /home/ubuntu/backend/dist/main.js --name backend -f
