
version: 2.1

jobs:
  build-frontend:
  
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: "Build Front End"
          command: |
            cd frontend
            npm install
            npm init -y
            npm run build
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend           


  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: "Build Back End"
          command: |
            cd backend
            npm install
            npm update
            npm init -y
            npm run build
      - save_cache:
          paths: [backend/node_modules]
          key: backend      
  
  test-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend]
      - run: 
          name: Front End test
          command: |
            cd frontend
            npm install
            npm init -y
            npm run test

  test-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend]
      - run: 
          name: Back End test
          command: |
            cd backend
            npm install
            npm update
            npm init -y
            npm run test

  scan-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend]
      - run: 
          name: scanning front end
          command: |
            cd frontend
            npm install
            npm init -y
            npm audit fix --audit-level=critical --force
            npm audit --audit-level=critical

  scan-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend]
      - run: 
          name: scanning backend end
          command: |
            cd backend
            npm install
            npm update
            npm init -y
            npm audit fix --audit-level=critical --force
            npm audit fix --force
            npm audit --audit-level=critical

workflows:
  say-hello-workflow:
    jobs:
#      - build-frontend
      - build-backend
#      - test-frontend:
#          requires: [build-frontend]
      - test-backend:
          requires: [build-backend]   
#      - scan-frontend:
#          requires: [build-frontend]
      - scan-backend:
          requires: [build-backend]      